version: '3.8'

services:
  telegram-bot:
    build: .
    container_name: "telegram-bot-${BOT_NAME:-default}"
    restart: unless-stopped
    
    # Переменные окружения из .env файла
    env_file:
      - .env
    
    # Маппинг портов (webhook порт)
    ports:
      - "${WEBHOOK_PORT:-8085}:${WEBHOOK_PORT:-8085}"
    
    # Подключение credentials файла
    volumes:
      - "./credentials.json:/app/credentials.json:ro"
      - "./logs:/app/logs"
    
    # Лимиты ресурсов
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    
    # Проверка здоровья
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${WEBHOOK_PORT:-8085}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Логирование
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
    # Сеть для изоляции
    networks:
      - telegram-bot-network

networks:
  telegram-bot-network:
    driver: bridge
    name: "telegram-bot-network-${BOT_NAME:-default}"
